version: "3"
services:
  web:
    image: nginx:1.19
    ports:
      - "8080:80"
    volumes:
      - ./:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    image: php-fpm-lavaral:7.4.0
    volumes:
      - ./:/code

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example_1234
      MYSQL_DATABASE: time_manage
      MYSQL_USER: time_manager
      MYSQL_PASSWORD: 1234